name: eeg2vec

dependencies:
  - python=3.10
  - pip=23.0.1
  - dask=2023.3.2
  - numpy=1.23.5
  - pandas==1.5.3
  - pyarrow=11.0.0
  - pytest=7.1.2
  - ipython=8.12.0
  - scikit-learn=1.2.2
  - networkx=2.8.4
  - pip:
    - ipykernel==6.22.0
    - db-dtypes==1.1.1
    - mne==1.3.1
    - google-cloud-storage==2.8.0
    - google-cloud-bigquery==3.10.0
    - charset-normalizer==3.1.0
    - gcsfs==2023.4.0
    - torch==1.13.1