name: eeg2vec

dependencies:
  - python=3.10.12
  - pip=23.2.1
  - dask=2023.8.1
  - numpy=1.23.5
  - pandas==2.0.3
  - pyarrow=12.0.1
  - pytest=7.4.0
  - ipython=8.14.0
  - scikit-learn=1.3.0
  - networkx=3.1
  - pip:
    - ipykernel==6.25.1
    - db-dtypes==1.1.1
    - mne==1.3.1
    - google-cloud-storage==2.10.0
    - google-cloud-bigquery==3.11.4
    - charset-normalizer==3.2.0
    - gcsfs==2023.6.0
    - torch==1.13.1
    - autoreject==0.4.2